name: Boat builder

on: [push]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
                include:
                    - os: ubuntu-latest
                      output-name: boat-linux
                    - os: macOS-latest
                      output-name: boat-mac
                    - os: windows-latest
                      output-name: boat-windows.exe

        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Setup Dart SDK
              uses: dart-lang/setup-dart@v1.3
            - run: pub get
            - name: Compile
              run: dart compile exe bin/main.dart -o build/${{ matrix.output-name }}
            - uses: actions/upload-artifact@v1
              with:
                  name: native-executables
                  path: build
