name: Boat builder

on: [push]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
                include:
                    - os: ubuntu-latest
                      output-boat: boat-linux
                      output-update: boat-update-linux
                    - os: macOS-latest
                      output-boat: boat-mac
                      output-update: boat-update-mac
                    - os: windows-latest
                      output-boat: boat-windows.exe
                      output-update: boat-update-windows.exe

        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Setup Dart SDK
              uses: dart-lang/setup-dart@v1.3
            - run: pub get
            - name: Compile Boat
              run: dart compile exe bin/main.dart -o build/${{ matrix.output-boat }}
            - name: Compile Boat update
              run: dart compile exe bin/update.dart -o build/${{ matrix.output-update }}
            - uses: actions/upload-artifact@v3
              with:
                  name: native-executables
                  path: build
